// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCW8x8QY4tY2DPKZ7_Mn6IH8fyzjoLSQk',
    appId: '1:633065681239:web:5fb3614ff152d4bbc6ce12',
    messagingSenderId: '633065681239',
    projectId: 'likee-897e9',
    authDomain: 'likee-897e9.firebaseapp.com',
    storageBucket: 'likee-897e9.appspot.com',
    measurementId: 'G-4G3B1K838G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJs91jyvLhvJsbgs_x96fhZOsDur9ssUE',
    appId: '1:633065681239:android:de48a17388172071c6ce12',
    messagingSenderId: '633065681239',
    projectId: 'likee-897e9',
    storageBucket: 'likee-897e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgjWikNz5DuXJS0uRaPo53LoBQdrdR2oE',
    appId: '1:633065681239:ios:a990fd1b37be2b5cc6ce12',
    messagingSenderId: '633065681239',
    projectId: 'likee-897e9',
    storageBucket: 'likee-897e9.appspot.com',
    iosBundleId: 'com.example.likee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgjWikNz5DuXJS0uRaPo53LoBQdrdR2oE',
    appId: '1:633065681239:ios:a990fd1b37be2b5cc6ce12',
    messagingSenderId: '633065681239',
    projectId: 'likee-897e9',
    storageBucket: 'likee-897e9.appspot.com',
    iosBundleId: 'com.example.likee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCW8x8QY4tY2DPKZ7_Mn6IH8fyzjoLSQk',
    appId: '1:633065681239:web:4e7ee2988282829cc6ce12',
    messagingSenderId: '633065681239',
    projectId: 'likee-897e9',
    authDomain: 'likee-897e9.firebaseapp.com',
    storageBucket: 'likee-897e9.appspot.com',
    measurementId: 'G-GBZ5SKF4DM',
  );
}
